#!/usr/bin/env node
// installer/merge-configs.mjs
//
// Static deep-merge of the global JSONC template on top of the project JSONC
// template, written as a single file the plugin runtime can consume directly.
// Mirrors `mergeObjects` from src/config/load-config.js — arrays in the
// project (override) layer fully REPLACE arrays in the global (base) layer.
// Inline comments from the source templates are dropped; a header comment
// block is prepended to the output file to explain its origin.

import fs from "node:fs";
import path from "node:path";

function parseArgs(argv) {
  const args = { global: null, project: null, out: null };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--global") args.global = argv[++i];
    else if (a === "--project") args.project = argv[++i];
    else if (a === "--out") args.out = argv[++i];
  }
  if (!args.global || !args.project || !args.out) {
    console.error(
      "Usage: merge-configs.mjs --global <path> --project <path> --out <path>",
    );
    process.exit(2);
  }
  return args;
}

function stripJsonComments(text) {
  return String(text || "")
    .replace(/^﻿/, "")
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/^\s*\/\/.*$/gm, "");
}

function mergeObjects(base, override) {
  if (!override || typeof override !== "object" || Array.isArray(override)) {
    return base;
  }
  const next = Array.isArray(base) ? [...base] : { ...base };
  for (const [key, value] of Object.entries(override)) {
    if (Array.isArray(value)) {
      next[key] = [...value];
      continue;
    }
    if (value && typeof value === "object") {
      const current =
        next[key] && typeof next[key] === "object" && !Array.isArray(next[key])
          ? next[key]
          : {};
      next[key] = mergeObjects(current, value);
      continue;
    }
    next[key] = value;
  }
  return next;
}

function readJsonc(filePath) {
  const text = fs.readFileSync(filePath, "utf8");
  return JSON.parse(stripJsonComments(text));
}

const { global: globalPath, project: projectPath, out: outPath } = parseArgs(
  process.argv.slice(2),
);

const globalRaw = readJsonc(globalPath);
const projectRaw = readJsonc(projectPath);
const merged = mergeObjects(globalRaw, projectRaw);

const header = [
  "// ────────────────────────────────────────────────────────────────────────────",
  "// DevAI AIDD Plugin — merged project config",
  "//",
  "// Generated by the installer with --project-path. This file is a static",
  "// deep-merge of the bundled global defaults and the project override",
  "// template, captured at install time:",
  `//   - global defaults:   ${path.basename(globalPath)}`,
  `//   - project overrides: ${path.basename(projectPath)}`,
  "//",
  "// Merge rules (same as the runtime mergeObjects in src/config/load-config.js):",
  "//   - Objects: deep-merged.",
  "//   - Arrays:  the project layer fully REPLACES the global layer.",
  "//",
  "// Inline comments from the source templates were dropped by the merge.",
  "// Edit this file directly to change policy for this project — the runtime",
  "// re-reads it on every workflow command.",
  "// ────────────────────────────────────────────────────────────────────────────",
  "",
].join("\n");

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, header + JSON.stringify(merged, null, 2) + "\n", "utf8");

console.log(`Merged config written to ${outPath}`);
